#### Solver for the Octogram Puzzle 

Utilizes backtracking to solve Octogram

In [1]:
import numpy as np

In [2]:
n_rows, n_cols = 8, 8

In [8]:
board = [[0 for i in range(n_rows)] for j in range(n_cols)]

In [38]:
class Piece:
    def __init__(self, orientations):
        self.orientation_index = 0
        self.orientations = orientations
        self.n_orientations = len(self.orientations)

    def reorient(self):
        self.orientation_index = (1 + self.orientation_index) % self.n_orientations

    def show(self):
        print(self.orientations[self.orientation_index])

In [45]:
import numpy as np

# Create all of the pieces in the Octogram Puzzle and place
# them into the pieces list.

# Initialize empty list to store all of the different pieces
pieces = []

# Piece One
orientations = [
    np.matrix([
        [1, 1],
        [1, 0],
        [1, 1]
        ]),
    np.matrix([
        [1, 1, 1],
        [1, 0, 1]
    ]),
    np.matrix([
        [1, 1],
        [0, 1],
        [1, 1]
    ]),
    np.matrix([
        [1, 0, 1],
        [1, 1, 1]
    ])
]

piece = Piece(orientations=orientations)
pieces.append(piece)





# Piece Two
orientations = [
    np.matrix([
        [1, 1],
        [1, 1]
    ])
]

piece = Piece(orientations=orientations)
pieces.append(piece)




# Piece Three
orientations = [
    np.matrix([
        [0, 1, 0],
        [1, 1, 1],
        [0, 1, 0]
    ])
]

piece = Piece(orientations=orientations)
pieces.append(piece)




# Piece Four
orientations = [
    np.matrix([
        [1, 1, 1],
        [0, 1, 0],
        [0, 1, 0]
        ]),
    np.matrix([
        [0, 0, 1],
        [1, 1, 1],
        [0, 0, 1]
    ]),
    np.matrix([
        [0, 1, 0],
        [0, 1, 0],
        [1, 1, 1]
    ]),
    np.matrix([
        [1, 0, 0],
        [1, 1, 1],
        [1, 0, 0]
    ])
]

piece = Piece(orientations=orientations)
pieces.append(piece)



# Piece Five
orientations = [
    np.matrix([
        [0, 0],
        [0, 0],
        [0, 0]
        ]),
    np.matrix([
        [0, 0],
        [0, 0],
        [0, 0]
        ]),
    np.matrix([
        [0, 0],
        [0, 0],
        [0, 0]
        ]),
    np.matrix([
        [0, 0],
        [0, 0],
        [0, 0]
        ]),
        np.matrix([
        [0, 0, 0],
        [0, 0, 0],
        ]),
    np.matrix([
        [0, 0, 0],
        [0, 0, 0],
    ]),
    np.matrix([
        [0, 0, 0],
        [0, 0, 0],
    ]),
    np.matrix([
        [0, 0, 0],
        [0, 0, 0],
    ])
]

piece = Piece(orientations=orientations)
pieces.append(piece)





In [53]:
piece.reorient()
piece.show()

[[0 1 0]
 [1 1 1]
 [0 1 0]]


In [20]:
# Piece Template for 3x2 and 2x3
orientations = [
    np.matrix([
        [0, 0],
        [0, 0],
        [0, 0]
        ]),
    np.matrix([
        [0, 0],
        [0, 0],
        [0, 0]
        ]),
    np.matrix([
        [0, 0],
        [0, 0],
        [0, 0]
        ]),
    np.matrix([
        [0, 0],
        [0, 0],
        [0, 0]
        ]),
        np.matrix([
        [0, 0, 0],
        [0, 0, 0],
        ]),
    np.matrix([
        [0, 0, 0],
        [0, 0, 0],
    ]),
    np.matrix([
        [0, 0, 0],
        [0, 0, 0],
    ]),
    np.matrix([
        [0, 0, 0],
        [0, 0, 0],
    ])
]

matrix([[1, 0, 1],
        [1, 1, 1]])